"""
Registrar -- CloudFormation Custom Resource that welds the Password Safe
managed account to the EC2 instance lifecycle.

  Create  -> wait for SSM readiness, read the per-instance SSH key
             AWS::EC2::KeyPair generated (environment.yaml), install its
             public half over SSM Run Command, onboard asset + managed
             system + managed account (carrying the private half), force an
             immediate rotation, reprocess both Smart Rules.
  Update  -> rotate + reprocess. Ids are stable.
  Delete  -> delete managed account and asset, reprocess. Idempotent; a
             missing object is success, not failure.

Why the key is read here rather than passed in from CloudFormation as a
plain value: a CFN parameter is visible in the console, in
`describe-stacks`, in the change set and in CloudTrail. AWS::EC2::KeyPair
instead stores the private half as an SSM SecureString that only this
function's role can decrypt; the only place the plaintext private key ever
exists is in this function's memory, briefly, en route to Password Safe.
After the first rotation (DSSAutoManagementFlag=true), even that seed key is
stale -- every key after it is generated by Password Safe itself.

DELETE MUST NOT THROW. A Custom Resource that fails on Delete leaves the
stack in DELETE_FAILED and a human has to go clean it up by hand. Every
failure on that path is logged and swallowed; orphan detection is the job of
scripts/reconcile.py, not of stack teardown.
"""

import json
import logging
import os
import time
import urllib.request

import boto3

import ec2_keypair
from passwordsafe import PasswordSafeClient, PasswordSafeError
from ssh_pubkey import openssh_public_key, KeyParseError

log = logging.getLogger()
log.setLevel(logging.INFO)

ssm = boto3.client("ssm")
secretsmanager = boto3.client("secretsmanager")

PS_BASE_URL = os.environ["PS_BASE_URL"]
PS_SECRET_ARN = os.environ["PS_SECRET_ARN"]

# Holds the functional account's PRIVATE key. Optional: if unset, the
# functional account must already exist in Password Safe and the registrar
# will only look it up, never create it.
PS_FUNCTIONAL_SECRET_ARN = os.environ.get("PS_FUNCTIONAL_SECRET_ARN") or None
FUNCTIONAL_PUBKEY_PARAM = os.environ.get(
    "FUNCTIONAL_PUBKEY_PARAM", "/ps-ephemeral/functional-account/public-key")

SSM_READY_TIMEOUT = int(os.environ.get("SSM_READY_TIMEOUT", "300"))
SSM_POLL_INTERVAL = 10
CMD_TIMEOUT = 120

CREATE_FAILED_SENTINEL = "CREATE_FAILED"


# --------------------------------------------------------------------------- #
# helpers
# --------------------------------------------------------------------------- #
def load_ps_credentials():
    """Bootstrap secret: the ONLY standing privilege in the whole design."""
    raw = secretsmanager.get_secret_value(SecretId=PS_SECRET_ARN)["SecretString"]
    doc = json.loads(raw)
    return doc["client_id"], doc["client_secret"]


def load_functional_credential():
    """
    Private half of the functional account's SSH key. Returns None if no
    secret is configured, in which case the account must already exist.
    """
    if not PS_FUNCTIONAL_SECRET_ARN:
        return {}
    raw = secretsmanager.get_secret_value(
        SecretId=PS_FUNCTIONAL_SECRET_ARN)["SecretString"]
    doc = json.loads(raw)
    return {
        "private_key": doc.get("private_key"),
        "passphrase": doc.get("passphrase"),
        "password": doc.get("password"),
    }


def read_public_key():
    """Public keys are not secrets, so this is a plain String parameter."""
    try:
        return ssm.get_parameter(Name=FUNCTIONAL_PUBKEY_PARAM)["Parameter"]["Value"]
    except ssm.exceptions.ParameterNotFound:
        return None


def wait_for_ssm(instance_id):
    """
    The real readiness gate. DependsOn only tells you the RunInstances API
    returned -- it says nothing about whether the box has booted. If we onboard
    before the host answers, the Password Safe test-connection fails and we
    would hand the team an account they cannot use.
    """
    deadline = time.time() + SSM_READY_TIMEOUT
    while time.time() < deadline:
        resp = ssm.describe_instance_information(
            Filters=[{"Key": "InstanceIds", "Values": [instance_id]}]
        )
        info = resp.get("InstanceInformationList", [])
        if info and info[0].get("PingStatus") == "Online":
            log.info("instance %s online in SSM", instance_id)
            return
        time.sleep(SSM_POLL_INTERVAL)
    raise TimeoutError(
        f"{instance_id} did not register with SSM within {SSM_READY_TIMEOUT}s"
    )


def run_command(instance_id, commands):
    cmd = ssm.send_command(
        InstanceIds=[instance_id],
        DocumentName="AWS-RunShellScript",
        Parameters={"commands": commands},
        TimeoutSeconds=CMD_TIMEOUT,
    )["Command"]["CommandId"]

    deadline = time.time() + CMD_TIMEOUT
    while time.time() < deadline:
        time.sleep(3)
        try:
            inv = ssm.get_command_invocation(
                CommandId=cmd, InstanceId=instance_id
            )
        except ssm.exceptions.InvocationDoesNotExist:
            continue
        if inv["Status"] in ("Success",):
            return inv
        if inv["Status"] in ("Failed", "Cancelled", "TimedOut"):
            # StandardErrorContent is safe to log: the password goes in via
            # stdin heredoc and is never echoed by chpasswd.
            raise RuntimeError(
                f"SSM command {inv['Status']}: {inv.get('StandardErrorContent','')[:500]}"
            )
    raise TimeoutError(f"SSM command {cmd} did not finish in {CMD_TIMEOUT}s")


def provision_functional_account(instance_id, username, public_key,
                                 elevation="sudo"):
    """
    Create the functional account ON THE INSTANCE and install the public half
    of the key whose private half lives in Password Safe.

    user-data already does this at boot; doing it again here is deliberate.
    user-data is best-effort and silent when it fails, and if this account is
    missing or its key is wrong then the very first rotation fails -- leaving a
    vaulted credential that does not actually work. Better to converge it now,
    synchronously, while we can still fail the stack.

    Sudo is restricted to the two binaries a password change needs. Full
    NOPASSWD:ALL would make this account a fleet-wide root equivalent.
    """
    script = [
        "set -euo pipefail",
        f"id -u {username} >/dev/null 2>&1 || useradd -m -s /bin/bash {username}",
        f"install -d -m 700 -o {username} -g {username} /home/{username}/.ssh",
        f"cat > /home/{username}/.ssh/authorized_keys <<'PUBKEY'",
        public_key,
        "PUBKEY",
        f"chown {username}:{username} /home/{username}/.ssh/authorized_keys",
        f"chmod 600 /home/{username}/.ssh/authorized_keys",
        f"cat > /etc/sudoers.d/90-{username} <<'SUDO'",
        f"{username} ALL=(root) NOPASSWD: /usr/sbin/chpasswd, /usr/bin/passwd",
        "SUDO",
        f"chmod 440 /etc/sudoers.d/90-{username}",
        "visudo -c >/dev/null",
        # Fail loudly here rather than at first rotation.
        f"test -s /home/{username}/.ssh/authorized_keys",
    ]
    run_command(instance_id, script)
    log.info("functional account %s converged on %s", username, instance_id)


def provision_local_account_with_key(instance_id, username, public_key):
    """
    Create (or converge) the managed account itself and install the public
    half of a key AWS generated -- see environment.yaml's per-instance
    AWS::EC2::KeyPair. The private half went from SSM straight into this
    function's caller and then into the Password Safe API call; it is never
    written to disk, a template, or an instance.

    No special sudo for this account -- it is the account BEING managed, not
    an elevation identity. Password Safe writes this account's *next* key
    into this same file by logging in as the functional account and
    elevating with ITS sudo rule (provision_functional_account), not this
    one. If that elevation rule turns out to be too narrow for Linux DSS key
    rotation, that shows up here, not on this account.
    """
    script = [
        "set -euo pipefail",
        f"id -u {username} >/dev/null 2>&1 || useradd -m -s /bin/bash {username}",
        f"install -d -m 700 -o {username} -g {username} /home/{username}/.ssh",
        f"cat > /home/{username}/.ssh/authorized_keys <<'PUBKEY'",
        public_key,
        "PUBKEY",
        f"chown {username}:{username} /home/{username}/.ssh/authorized_keys",
        f"chmod 600 /home/{username}/.ssh/authorized_keys",
        # Key auth only for this account -- there is no password to fall
        # back to, so leaving password auth on would just be an unused,
        # unaudited second door.
        f"passwd -l {username} >/dev/null 2>&1 || true",
        f"test -s /home/{username}/.ssh/authorized_keys",
    ]
    run_command(instance_id, script)
    log.info("managed account %s key-provisioned on %s", username, instance_id)


def reprocess_rules(ps, cfg):
    """Best-effort: a rule that will not reprocess must not fail the stack."""
    for title in (cfg["smartRuleSystems"], cfg["smartRuleAccounts"]):
        try:
            rule = ps.find_smart_rule(title)
            if rule:
                ps.process_smart_rule(rule["SmartRuleID"])
                log.info("reprocessed smart rule %s", title)
            else:
                log.warning("smart rule %r not found -- team will not see this "
                            "host until it exists", title)
        except PasswordSafeError as exc:
            log.warning("smart rule %s reprocess failed: %s", title, exc)


# --------------------------------------------------------------------------- #
# lifecycle
# --------------------------------------------------------------------------- #
def on_create(props):
    cfg = json.loads(props["Config"]) if isinstance(props["Config"], str) \
        else props["Config"]
    instance_id = props["InstanceId"]
    private_ip = props["PrivateIp"]
    asset_name = props["AssetName"]
    account_name = cfg.get("localAccountName", "ec2-svc")
    key_pair_id = props["KeyPairId"]

    functional_name = cfg.get("functionalAccountName", "ps-rotator")

    wait_for_ssm(instance_id)

    # 1. Functional account on the box, so Password Safe has a way in.
    functional_public_key = read_public_key()
    if functional_public_key:
        provision_functional_account(instance_id, functional_name,
                                     functional_public_key,
                                     cfg.get("elevationCommand", "sudo"))
    else:
        log.warning("no public key at %s -- relying on user-data having "
                    "provisioned %s correctly", FUNCTIONAL_PUBKEY_PARAM,
                    functional_name)

    # 2. The managed account itself. AWS::EC2::KeyPair (environment.yaml)
    # generated this key, not this function -- we read the private half
    # once, in memory, to hand to Password Safe below, and derive the public
    # half to install on the box. Neither half is ever written to
    # CloudFormation, a template parameter, or anywhere on local disk.
    private_key = ec2_keypair.read_private_key(ssm, key_pair_id)
    try:
        public_key = openssh_public_key(private_key, comment=account_name)
    except KeyParseError as exc:
        raise RuntimeError(f"could not derive public key from EC2 key pair "
                           f"{key_pair_id}: {exc}") from exc
    provision_local_account_with_key(instance_id, account_name, public_key)

    client_id, client_secret = load_ps_credentials()
    with PasswordSafeClient(PS_BASE_URL, client_id, client_secret) as ps:
        wg = ps.get_workgroup(cfg["workgroupName"])
        workgroup_id = wg.get("ID") or wg.get("WorkgroupID")
        platform = ps.get_platform(cfg.get("platformName", "Linux"))
        platform_id = platform["PlatformID"]

        # 3. Functional account in the vault. Password Safe rotates the managed
        # account by logging in AS this identity, so FunctionalAccountID is
        # mandatory whenever AutoManagementFlag is true.
        #
        # One object serves the whole fleet: get-or-create, never create-again.
        functional_account_id = ps.ensure_functional_account(
            platform, functional_name,
            elevation_command=cfg.get("elevationCommand", "sudo"),
            description="ps-ephemeral-ec2 rotation identity",
            **load_functional_credential(),
        )

        # One call: the managed system is created directly in the Workgroup,
        # so it can never briefly exist outside the team's Smart Rule scope.
        system = ps.create_managed_system_in_workgroup(
            workgroup_id, platform_id, functional_account_id,
            system_name=asset_name,
            ip_address=private_ip,
            dns_name=props.get("PrivateDnsName") or asset_name,
            cfg=cfg,
        )
        system_id = system["ManagedSystemID"]

        account = ps.create_managed_account(
            system_id, account_name, cfg, platform=platform,
            private_key=private_key, workgroup_id=workgroup_id)
        account_id = account["ManagedAccountID"]

        # Force an immediate rotation now, rather than waiting for Password
        # Safe's own DSS rotation schedule (which may be weeks away, see
        # cfg.changeFrequencyType) to be the first time anyone discovers a
        # broken Resource Broker path or an elevation problem.
        #
        # DSSAutoManagementFlag=true means Password Safe now generates and
        # installs this account's NEXT key itself, by logging in as the
        # functional account and elevating with ITS sudo rule. That rule is
        # currently scoped to chpasswd/passwd (see provision_functional_account
        # and environment.yaml's user-data) -- which is known-sufficient for
        # PASSWORD rotation but has NOT been confirmed sufficient for writing
        # a Linux account's ~/.ssh/authorized_keys. If this fails, that is the
        # first thing to check -- see docs/RUNBOOK.md section 1b for how to
        # find the exact command Password Safe tried to run and widen the
        # sudoers rule to match.
        try:
            ps.rotate_credential(account_id)
        except PasswordSafeError as exc:
            log.warning("INITIAL KEY ROTATION FAILED (%s) for %s. Check: (1) "
                        "the functional account can reach %s on port %s, "
                        "(2) its sudo rule can write %s's authorized_keys -- "
                        "see docs/RUNBOOK.md section 1b.", exc, account_name,
                        private_ip, cfg.get("port", 22), account_name)

        reprocess_rules(ps, cfg)

    physical_id = f"{system_id}:{account_id}"
    log.info("onboarded %s as %s", asset_name, physical_id)
    return physical_id, {
        "ManagedSystemId": str(system_id),
        "ManagedAccountId": str(account_id),
        "AccountName": account_name,
        "Workgroup": cfg["workgroupName"],
    }


def on_update(physical_id, props):
    """Ids are stable across updates -- never return a new PhysicalResourceId
    here, or CloudFormation will schedule a Delete on the old one."""
    cfg = json.loads(props["Config"]) if isinstance(props["Config"], str) \
        else props["Config"]
    try:
        _system_id, account_id = physical_id.split(":")
    except ValueError:
        log.warning("unparseable physical id %r on update -- no-op", physical_id)
        return physical_id, {}

    client_id, client_secret = load_ps_credentials()
    with PasswordSafeClient(PS_BASE_URL, client_id, client_secret) as ps:
        try:
            ps.rotate_credential(int(account_id))
        except PasswordSafeError as exc:
            log.warning("rotation on update failed: %s", exc)
        reprocess_rules(ps, cfg)
    return physical_id, {"ManagedAccountId": account_id}


def on_delete(physical_id, props):
    """Never raises. See module docstring."""
    if not physical_id or physical_id.startswith(CREATE_FAILED_SENTINEL):
        log.info("nothing was ever created -- delete is a no-op")
        return

    try:
        system_id, account_id = physical_id.split(":")
    except ValueError:
        log.warning("unparseable physical id %r -- nothing to deregister",
                    physical_id)
        return

    try:
        cfg = json.loads(props["Config"]) if isinstance(props.get("Config"), str) \
            else props.get("Config", {})
        client_id, client_secret = load_ps_credentials()
        with PasswordSafeClient(PS_BASE_URL, client_id, client_secret) as ps:
            # Account first, then its system. Both are idempotent; a 404 on
            # either is treated as already-done.
            ps.delete_managed_account(int(account_id))
            ps.delete_managed_system(int(system_id))
            if cfg:
                reprocess_rules(ps, cfg)
        log.info("deregistered %s", physical_id)
    except Exception as exc:                       # noqa: BLE001 - intentional
        log.error("DEREGISTRATION FAILED for %s: %s -- stack delete will "
                  "continue. Run scripts/reconcile.py to clean up the orphan.",
                  physical_id, exc)


# --------------------------------------------------------------------------- #
# CloudFormation plumbing
# --------------------------------------------------------------------------- #
def send_response(event, context, status, physical_id, data=None, reason=None):
    body = json.dumps({
        "Status": status,
        "Reason": reason or f"See CloudWatch log stream {context.log_stream_name}",
        "PhysicalResourceId": physical_id,
        "StackId": event["StackId"],
        "RequestId": event["RequestId"],
        "LogicalResourceId": event["LogicalResourceId"],
        "NoEcho": False,
        "Data": data or {},
    }).encode()

    req = urllib.request.Request(
        event["ResponseURL"], data=body, method="PUT",
        headers={"content-type": "", "content-length": str(len(body))},
    )
    with urllib.request.urlopen(req, timeout=30) as resp:
        log.info("cfn response %s -> %s", status, resp.status)


def lambda_handler(event, context):
    log.info("request: %s", json.dumps(
        {k: v for k, v in event.items() if k != "ResponseURL"}))

    request_type = event["RequestType"]
    props = event.get("ResourceProperties", {})
    physical_id = event.get("PhysicalResourceId")
    data = {}

    try:
        if request_type == "Create":
            physical_id, data = on_create(props)
        elif request_type == "Update":
            physical_id, data = on_update(physical_id, props)
        elif request_type == "Delete":
            on_delete(physical_id, props)
        else:
            raise ValueError(f"unknown RequestType {request_type}")

        send_response(event, context, "SUCCESS", physical_id, data)

    except Exception as exc:                       # noqa: BLE001
        log.exception("registrar failed")
        if request_type == "Delete":
            # Belt and braces: even an unexpected failure must not wedge the
            # stack in DELETE_FAILED.
            send_response(event, context, "SUCCESS",
                          physical_id or CREATE_FAILED_SENTINEL,
                          reason=f"delete tolerated failure: {exc}")
        else:
            send_response(event, context, "FAILED",
                          physical_id or CREATE_FAILED_SENTINEL,
                          reason=str(exc)[:900])
